// Mocks generated by Mockito 5.2.0 from annotations
// in softwaretutorials/test/infrastructure/profile_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:softwaretutorials/domain/core/models.dart' as _i3;
import 'package:softwaretutorials/infrastructure/local_repository/local_data_provider.dart'
    as _i2;
import 'package:softwaretutorials/infrastructure/local_repository/user_local_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeLocalDataProvider_0 extends _i1.Fake
    implements _i2.LocalDataProvider {}

class _FakeUser_1 extends _i1.Fake implements _i3.User {}

/// A class which mocks [UserLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalRepository extends _i1.Mock
    implements _i4.UserLocalRepository {
  MockUserLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalDataProvider get dbProvider =>
      (super.noSuchMethod(Invocation.getter(#dbProvider),
          returnValue: _FakeLocalDataProvider_0()) as _i2.LocalDataProvider);
  @override
  _i5.Future<int> createUser(_i3.User? user) =>
      (super.noSuchMethod(Invocation.method(#createUser, [user]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<List<_i3.User>> getAllUsers() =>
      (super.noSuchMethod(Invocation.method(#getAllUsers, []),
              returnValue: Future<List<_i3.User>>.value(<_i3.User>[]))
          as _i5.Future<List<_i3.User>>);
  @override
  _i5.Future<int> updateUser(_i3.User? user) =>
      (super.noSuchMethod(Invocation.method(#updateUser, [user]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<_i3.User> getUser(String? username) =>
      (super.noSuchMethod(Invocation.method(#getUser, [username]),
              returnValue: Future<_i3.User>.value(_FakeUser_1()))
          as _i5.Future<_i3.User>);
  @override
  _i5.Future<int> deleteUser(String? username) =>
      (super.noSuchMethod(Invocation.method(#deleteUser, [username]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
}
