// Mocks generated by Mockito 5.2.0 from annotations
// in softwaretutorials/test/presentation/bloctest/tutorial_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:softwaretutorials/domain/auth/repo_response.dart' as _i2;
import 'package:softwaretutorials/domain/core/models.dart' as _i6;
import 'package:softwaretutorials/infrastructure/local_repository/local_data_provider.dart'
    as _i3;
import 'package:softwaretutorials/infrastructure/local_repository/tutorial_local_repository.dart'
    as _i9;
import 'package:softwaretutorials/infrastructure/tutorials/enrollement_service.dart'
    as _i7;
import 'package:softwaretutorials/infrastructure/tutorials/profile_service.dart'
    as _i4;
import 'package:softwaretutorials/infrastructure/tutorials/tutorial_service.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeRepoResponse_0 extends _i1.Fake implements _i2.RepoResponse {}

class _FakeLocalDataProvider_1 extends _i1.Fake
    implements _i3.LocalDataProvider {}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i4.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.RepoResponse> signup(
          {String? email,
          String? username,
          dynamic fullName,
          String? password,
          String? role}) =>
      (super.noSuchMethod(
              Invocation.method(#signup, [], {
                #email: email,
                #username: username,
                #fullName: fullName,
                #password: password,
                #role: role
              }),
              returnValue:
                  Future<_i2.RepoResponse>.value(_FakeRepoResponse_0()))
          as _i5.Future<_i2.RepoResponse>);
  @override
  _i5.Future<_i2.RepoResponse> updateProfile(
          {String? email,
          String? username,
          dynamic fullName,
          String? password}) =>
      (super.noSuchMethod(
              Invocation.method(#updateProfile, [], {
                #email: email,
                #username: username,
                #fullName: fullName,
                #password: password
              }),
              returnValue:
                  Future<_i2.RepoResponse>.value(_FakeRepoResponse_0()))
          as _i5.Future<_i2.RepoResponse>);
  @override
  _i5.Future<List<_i6.User>> getAllUsers() =>
      (super.noSuchMethod(Invocation.method(#getAllUsers, []),
              returnValue: Future<List<_i6.User>>.value(<_i6.User>[]))
          as _i5.Future<List<_i6.User>>);
  @override
  _i5.Future<bool> deleteUser(int? userId) =>
      (super.noSuchMethod(Invocation.method(#deleteUser, [userId]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i6.User?> getUserProfile() =>
      (super.noSuchMethod(Invocation.method(#getUserProfile, []),
          returnValue: Future<_i6.User?>.value()) as _i5.Future<_i6.User?>);
}

/// A class which mocks [EnrollementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnrollementRepository extends _i1.Mock
    implements _i7.EnrollementRepository {
  MockEnrollementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String?> enroll({int? tutorialId}) => (super.noSuchMethod(
      Invocation.method(#enroll, [], {#tutorialId: tutorialId}),
      returnValue: Future<String?>.value()) as _i5.Future<String?>);
  @override
  _i5.Future<String?> unenroll({int? tutorialId}) => (super.noSuchMethod(
      Invocation.method(#unenroll, [], {#tutorialId: tutorialId}),
      returnValue: Future<String?>.value()) as _i5.Future<String?>);
}

/// A class which mocks [TutorialRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTutorialRepository extends _i1.Mock
    implements _i8.TutorialRepository {
  MockTutorialRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Tutorial>> getAllTutorials() =>
      (super.noSuchMethod(Invocation.method(#getAllTutorials, []),
              returnValue: Future<List<_i6.Tutorial>>.value(<_i6.Tutorial>[]))
          as _i5.Future<List<_i6.Tutorial>>);
  @override
  _i5.Future<_i6.Tutorial?> getTutorial(int? tutorialId) => (super.noSuchMethod(
      Invocation.method(#getTutorial, [tutorialId]),
      returnValue: Future<_i6.Tutorial?>.value()) as _i5.Future<_i6.Tutorial?>);
  @override
  _i5.Future<List<_i6.Tutorial>> getEnrolledTutorials() =>
      (super.noSuchMethod(Invocation.method(#getEnrolledTutorials, []),
              returnValue: Future<List<_i6.Tutorial>>.value(<_i6.Tutorial>[]))
          as _i5.Future<List<_i6.Tutorial>>);
  @override
  _i5.Future<List<_i6.Tutorial>> getMyTutorials() =>
      (super.noSuchMethod(Invocation.method(#getMyTutorials, []),
              returnValue: Future<List<_i6.Tutorial>>.value(<_i6.Tutorial>[]))
          as _i5.Future<List<_i6.Tutorial>>);
  @override
  _i5.Future<bool> createTutorial(
          {String? title,
          String? content,
          String? projectTitle,
          String? problemStatement}) =>
      (super.noSuchMethod(
          Invocation.method(#createTutorial, [], {
            #title: title,
            #content: content,
            #projectTitle: projectTitle,
            #problemStatement: problemStatement
          }),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<bool> updateTutorial(
          {String? title,
          String? content,
          String? projectTitle,
          String? problemStatement,
          int? tutorialId}) =>
      (super.noSuchMethod(
          Invocation.method(#updateTutorial, [], {
            #title: title,
            #content: content,
            #projectTitle: projectTitle,
            #problemStatement: problemStatement,
            #tutorialId: tutorialId
          }),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<bool> deleteTutorial({int? tutorialId}) => (super.noSuchMethod(
      Invocation.method(#deleteTutorial, [], {#tutorialId: tutorialId}),
      returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [TutorialLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTutorialLocalRepository extends _i1.Mock
    implements _i9.TutorialLocalRepository {
  MockTutorialLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.LocalDataProvider get dbProvider =>
      (super.noSuchMethod(Invocation.getter(#dbProvider),
          returnValue: _FakeLocalDataProvider_1()) as _i3.LocalDataProvider);
  @override
  _i5.Future<int> createTutorial(_i6.Tutorial? tutorial) =>
      (super.noSuchMethod(Invocation.method(#createTutorial, [tutorial]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<List<_i6.Tutorial>> getAllTutorials() =>
      (super.noSuchMethod(Invocation.method(#getAllTutorials, []),
              returnValue: Future<List<_i6.Tutorial>>.value(<_i6.Tutorial>[]))
          as _i5.Future<List<_i6.Tutorial>>);
  @override
  _i5.Future<int> updateTutorial(_i6.Tutorial? tutorial) =>
      (super.noSuchMethod(Invocation.method(#updateTutorial, [tutorial]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<int> deleteTutorial(int? tutorialId) =>
      (super.noSuchMethod(Invocation.method(#deleteTutorial, [tutorialId]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
}
